# Generated by Django 4.2.13 on 2024-05-17 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "Currencies"},
        ),
    ]
