# Generated by Django 4.2.13 on 2024-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0002_alter_currency_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_code", models.PositiveIntegerField()),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
                (
                    "buy_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "sell_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "cross_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
