# Generated by Django 4.2.13 on 2024-05-21 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0003_currencyhistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CurrencyHistory",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="last_update",
        ),
        migrations.AddField(
            model_name="currency",
            name="date_recorded",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="currency",
            name="is_tracked",
            field=models.BooleanField(default=True),
        ),
    ]
