# Generated by Django 4.2.13 on 2024-05-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0004_delete_currencyhistory_remove_currency_last_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="date_recorded",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
