# Generated by Django 4.2.13 on 2024-05-21 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0005_alter_currency_date_recorded"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currency",
            name="date_recorded",
        ),
        migrations.AddField(
            model_name="currency",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="currency",
            name="is_tracked",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CurrencyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buy_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("sell_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("cross_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rates.currency"
                    ),
                ),
            ],
        ),
    ]
