# Generated by Django 4.2.13 on 2024-05-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rates", "0006_remove_currency_date_recorded_currency_date_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currencyhistory",
            name="buy_rate",
        ),
        migrations.RemoveField(
            model_name="currencyhistory",
            name="cross_rate",
        ),
        migrations.RemoveField(
            model_name="currencyhistory",
            name="sell_rate",
        ),
        migrations.AddField(
            model_name="currencyhistory",
            name="rates",
            field=models.JSONField(null=True),
        ),
    ]
